kind: pipeline
type: docker
name: tidy

steps:
  - name: tidy
    image: notgull/ci:stable
    pull: true
    commands:
      - tidy.sh
---
kind: pipeline
type: docker
name: test-stable

depends_on:
  - tidy

steps:
  - name: test
    image: notgull/ci:stable
    pull: always
    commands:
      - test_rust.sh --skip-ndf libm
---
kind: pipeline
type: docker
name: test-beta

depends_on:
  - tidy

steps:
  - name: test
    image: notgull/ci:beta
    pull: always
    commands:
      - test_rust.sh --skip-ndf libm
---
kind: pipeline
type: docker
name: test-nightly

depends_on:
  - tidy

steps:
  - name: test
    image: notgull/ci:nightly
    pull: always
    commands:
      - test_rust.sh --skip-ndf libm
---
kind: pipeline
type: docker
name: test-msrv

depends_on:
  - tidy

steps:
  - name: test
    image: notgull/ci:1.63.0
    pull: always
    commands:
      - test_rust.sh --skip-ndf libm
---
kind: pipeline
type: docker
name: release

trigger:
  branch:
    - main
  event:
    - push

depends_on:
  - test-stable
  - test-beta
  - test-nightly
  - test-msrv

steps:
  - name: check_tag
    image: notgull/ci:stable
    commands:
      - is_release.sh
  - name: gitea_release
    image: alpine:edge
    environment:
      SSH_KEY:
        from_secret: tea_ssh_key
      TEA_CONFIG:
        from_secret: tea_config_yml
    commands:
      - apk add git tea
      - mkdir -pv ~/.ssh && mkdir -pv ~/.config/tea
      - echo "$SSH_KEY" > ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa
      - echo "$TEA_CONFIG" > ~/.config/tea/config.yml
      - tea release create --title "$(git describe --tags "$(git rev-parse HEAD)")" -n "notes"
---
kind: pipeline
type: docker
name: github

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: mirror to GitHub
    image: alpine:edge
    environment:
      SSH_KEY:
        from_secret: gh_ssh_key
    commands:
      - apk add git openssh
      - mkdir -pv ~/.ssh
      - ssh-keyscan -H -t rsa github.com >> ~/.ssh/known_hosts
      - echo "$SSH_KEY" > ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa
      - git remote add github_origin git@github.com:notgull/line-straddler.git
      - git push github_origin main
